[package]
name = "rust-web-server-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
cargo-watch = "8.5.2"
chrono = "0.4.38"
futures-util = "0.3.30"
mongodb = "3.0.1"
serde = "1.0.205"
